### PR TITLE
Added Quadratic to Program.cs and Quadratic readme (YParkhomenko)

### PR DESCRIPTION
**Pull request by frostysh**
I have added Quadratic into Program.cs, a source code for the program that trying to solve quadratic equations with use of try-catch-finally construction, (my first computer program actually), and then some spaces #823ad367, also initial "Hello World!" has been changed #e769c1f1, added Readme_Quadratic file.

### CODE REVIEW

**Comment by frostysh** [comment]
Initial push, waiting for merge-conflicts... 🍶 :S

**Comment by DMIbragimoov** [comment]
LGTM

**Review by DMIbragimoov — APPROVED** [review]
LGTM

**Comment by frostysh** [comment]
Approve киньте, не тільки коменти... :)

**Review by olegkarman — APPROVED** [review]

**Review by NinaBabi — APPROVED** [review]

**Comment by frostysh** [comment]
Писець, знову конфлікти, ну ладно...

**Pull request merged**
